### ISSUE TITLE
Germanet depends on yanked version of python-Levenshtein

### ISSUE THREAD

**Issue by pikatech** [Germanet-sfs/germanetpy#3]
While installing a project that depends on germanetpy 0.2.1, I've encountered the following warning:

WARNING: The candidate selected for download or install is a yanked version: 'python-Levenshtein' candidate (version 0.12.0 at https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz#sha256=033a11de5e3d19ea25c9302d11224e1a1898fe5abd23c61c7c360c25195e3eb1 (from https://pypi.org/simple/python-levenshtein/))
Reason for being yanked: Insecure, upgrade to 0.12.1

Even though the message says 'upgrade to 0.12.1', version 0.12.2 is already available on PyPI.

How to fix it:
Replace this line in setup.py

requirements = ["numpy>=1.18.1", "lxml>=4.4.2", "pytest>=5.3.2", "fastenum>=0.0.1", "tqdm>=4.14",
                "python-Levenshtein==0.12.0"]

with
requirements = ["numpy>=1.18.1", "lxml>=4.4.2", "pytest>=5.3.2", "fastenum>=0.0.1", "tqdm>=4.14",
                "python-Levenshtein==0.12.2"]

**Comment by bencampbell30** [comment]
Fixed.
