### ISSUE TITLE
Is there a type error in a logging message?

### ISSUE THREAD

**Issue by chlor** [Germanet-sfs/germanetpy#4]
There is a type error in a logging message:

https://github.com/Germanet-sfs/germanetpy/blob/master/germanetpy/germanet.py
Line 193
`pbar = trange(100, desc='Load Wictionary data...', leave=True)`

During a run, it is a little bit confusing, because 'Wiktionary' is typed with K in the middle of the word and not with a C.

**Comment by bencampbell30** [comment]
Fixed
